name:                tholid
version:             0.1.0
synopsis:            The obligatory lisp interpreter
license:             GPL-3
author:              Tony Zorman
maintainer:          soliditsallgood@mailbox.org
homepage:            TODO

ghc-options:
  -Weverything
  -Wno-implicit-prelude
  -Wno-missing-import-lists
  -Wno-unused-packages
  -Wno-missing-safe-haskell-mode
  -Wno-all-missed-specialisations
  -Wno-unsafe
  -O2

language: GHC2021

default-extensions:
  - ImportQualifiedPost
  - FlexibleContexts
  - GADTs
  - OverloadedStrings
  - LambdaCase
  - DerivingStrategies
  - GeneralizedNewtypeDeriving
  - BlockArguments
  - UndecidableInstances
  - InstanceSigs
  - ScopedTypeVariables
  - TupleSections
  - StandaloneKindSignatures
  - ConstraintKinds
  - RankNTypes

dependencies:
  - base
  - containers
  - text
  - transformers
  - mtl
  - megaparsec

library:
  source-dirs: src

executables:
  tholid:
    source-dirs: app
    main: Main.hs
    dependencies: tholid
