name:                tholid
version:             0.1.0
synopsis:            The obligatory lisp interpreter
license:             GPL-3
author:              Tony Zorman
maintainer:          soliditsallgood@mailbox.org
homepage:            TODO

ghc-options:
  -Weverything
  -Wno-implicit-prelude
  -Wno-missing-import-lists
  -Wno-unused-packages
  -Wno-missing-safe-haskell-mode
  -Wno-all-missed-specialisationsa
  -Wno-unsafe
  -O2

default-extensions:
  - ImportQualifiedPost
  - FlexibleContexts
  - GADTSyntax
  - OverloadedStrings
  - LambdaCase
  - DerivingStrategies
  - GeneralizedNewtypeDeriving
  - BlockArguments
  - UndecidableInstances
  - InstanceSigs
  - ScopedTypeVariables
  - TupleSections

dependencies:
  - base
  - containers
  - text
  - transformers
  - mtl
  - megaparsec
  - unliftio

library:
  source-dirs: src

executables:
  tholid:
    source-dirs: app
    main: Main.hs
    dependencies: tholid
